# Generated by Django 4.0.3 on 2022-03-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(blank=True, default=0, verbose_name='مبلغ واحد')),
                ('controller', models.PositiveBigIntegerField(blank=True, default=15)),
                ('id_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel', verbose_name='نام محصول')),
                ('id_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
