# Generated by Django 4.0.3 on 2022-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='gender',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
