# Generated by Django 4.0.3 on 2022-04-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profilemodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
