# Generated by Django 4.0.3 on 2022-04-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profilemodel_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
