# Generated by Django 4.0.3 on 2022-05-05 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_alter_transactions_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 6, 0, 55, 23, 464488), verbose_name='تاریخ پرداخت'),
        ),
    ]
