# Generated by Django 4.0.3 on 2022-06-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_blogslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='BlogSlug',
            new_name='slug',
        ),
    ]
