# Generated by Django 4.0.3 on 2022-03-20 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=99, size=[1920, 1080], upload_to='MainCategories', verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='دسته بندی پدر')),
            ],
        ),
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=60, verbose_name='نام محصول')),
                ('ProductBody', models.TextField(max_length=800, verbose_name='توضیحات محصول ۱')),
                ('ProductBody2', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات محصول ۲')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=99, size=[1920, 1080], upload_to=shop.models.upload_image_path, verbose_name='عکس ۱')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_image_path, verbose_name='عکس ۲')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_image_path, verbose_name='عکس ۳')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_image_path, verbose_name='عکس ۴')),
                ('image5', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_image_path, verbose_name='عکس ۵')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('deleted', models.BooleanField(default=False, verbose_name='پاک شده')),
                ('firstpage', models.BooleanField(blank=True, default=False, null=True, verbose_name='صفحه اول')),
                ('show_price', models.CharField(blank=True, default='0', max_length=5, verbose_name='قیمت تکه شده')),
                ('Seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategories', verbose_name='زیر دسته بندی')),
                ('categoryMain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(max_length=1000, verbose_name='توضیح')),
                ('commentposted', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='کامنت پست بشود؟')),
                ('motherpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel', verbose_name='پست مادر')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
