# Generated by Django 4.0.3 on 2022-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='show_price',
            field=models.CharField(blank=True, default='0', max_length=500, verbose_name='قیمت تکه شده'),
        ),
    ]
